[solver.equation]
    solver = 'pressureProjection'

[solver.fluid]
    nu  = 0.08797
    rho = 1.0

[solver.time]
    dt        = 0.3
    timesteps = 100

[solver.schemes]
    timeIntegrationScheme = 'secondOrderBackwards'
    nonLinearScheme       = 'secondOrderUpwind'
    diffusionScheme       = 'secondOrderCentral'

[solver.linearSolver]
    solver          = {u = "BCGS", v = "BCGS", p = "BCGS"}
    preconditioner  = {u = "ILU",  v = "ILU",  p = "ILU"}
    tolerance       = {u = 1e-10,  v = 1e-10,  p = 1e-10}
    maxIterations   = {u = 1000,   v = 1000,   p = 1000}
    underRelaxation = {u = 1.0,    v = 1.0,    p = 1.0}

[solver.convergence]
    picardIterations      = 1
    picard_tolerance      = {u = 1e-3, v = 1e-3, p = 1e-3}
    convergence_tolerance = {u = 1e-8, v = 1e-8, p = 1e-8}

[solver.output]
    filename         = "training_13"
    writingFrequency = 0

[solver.ML]
    generateTrainingData = true
    trainingVariables    = ['u', 'v', 'p']

[mesh.block1]
    x = {start = 0.0, end = 1.0, numCells = 64}
    y = {start = 0.0, end = 1.0, numCells = 64}

[boundaryCondition.block1]
    east  = {u = {type = "dirichlet", value = 0.0}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}
    west  = {u = {type = "dirichlet", value = 0.0}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}
    north = {u = {type = "dirichlet", value = 1.0049}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}
    south = {u = {type = "dirichlet", value = 0.0}, v = {type = "dirichlet", value = 0.0}, p = {type = "neumann", value = 0.0}}
